name: CI ASV check

on: 
  push:
    paths:
      - 'benchmarks/benchmarks/**'
  pull_request:
    paths:
      - 'benchmarks/benchmarks/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.7'

      - name: Install asv
        run:  pip install asv

      - name: Run asv benchmarks
        run: |
          cd benchmarks
          asv machine --yes
          asv run --quick --dry-run --strict --durations=30 --python=same
        
